/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication2;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class addData extends javax.swing.JFrame {
    String connectionUr1
                = "jdbc:sqlserver://LAPTOP-77JR298K;"
                + "database=Projek_Basdat;"
                + "user=sa;"
                + "password=mdaf;"
                + "encrypt=true;"
                + "trustServerCertificate=true;"
                + "loginTimeout=30;";
    /**
     * Creates new form addData
     */
    public addData() {
        initComponents();
        bodyCapSpnr.setEnabled(false);
        hotShoeSpnr.setEnabled(false);
        lensCapSpnr.setEnabled(false);
        rearCapSpnr.setEnabled(false);
        taliSpnr.setEnabled(false);
        filterUVSpnr.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        noNotaTxt = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        KodeUnit = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        KsiUnit = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        alamatToko = new javax.swing.JComboBox<>();
        namaPelanggan = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        noHP = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        alamat = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        keluhan = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        tanggalD = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        merek = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        tanggalM = new javax.swing.JTextField();
        tanggalY = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        bodyCapCB = new javax.swing.JCheckBox();
        hotShoeCB = new javax.swing.JCheckBox();
        rearCapCB = new javax.swing.JCheckBox();
        taliCB = new javax.swing.JCheckBox();
        lensCapCB = new javax.swing.JCheckBox();
        filterUVCB = new javax.swing.JCheckBox();
        bodyCapSpnr = new javax.swing.JSpinner();
        hotShoeSpnr = new javax.swing.JSpinner();
        lensCapSpnr = new javax.swing.JSpinner();
        rearCapSpnr = new javax.swing.JSpinner();
        taliSpnr = new javax.swing.JSpinner();
        filterUVSpnr = new javax.swing.JSpinner();
        addBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        statusPengambilan = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        ketPeng = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel19.setText("No. Nota");

        noNotaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noNotaTxtActionPerformed(evt);
            }
        });

        jLabel20.setText("Kode Unit");

        KodeUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KodeUnitActionPerformed(evt);
            }
        });

        jLabel21.setText("Kondisi Unit");

        KsiUnit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baik", "Lecet", "Rusak" }));
        KsiUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KsiUnitActionPerformed(evt);
            }
        });

        jLabel22.setText("Alamat Toko");

        alamatToko.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jalan Cianjur", "Jalan Trunojoyo" }));
        alamatToko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamatTokoActionPerformed(evt);
            }
        });

        namaPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaPelangganActionPerformed(evt);
            }
        });

        jLabel23.setText("Status Pengambilan");

        jLabel24.setText("Nama Pelanggan");

        noHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noHPActionPerformed(evt);
            }
        });

        jLabel25.setText("Alamat Pelanggan");

        alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamatActionPerformed(evt);
            }
        });

        jLabel26.setText("No. HP Pelanggan");

        jLabel27.setText("Keluhan");

        keluhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluhanActionPerformed(evt);
            }
        });

        jLabel28.setText("Keterangan Pengerjaan");

        tanggalD.setText("DD");
        tanggalD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanggalDActionPerformed(evt);
            }
        });

        jLabel29.setText("Merek/Model");

        merek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                merekActionPerformed(evt);
            }
        });

        jLabel30.setText("Tanggal");

        tanggalM.setText("MM");
        tanggalM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanggalMActionPerformed(evt);
            }
        });

        tanggalY.setText("YYYY");
        tanggalY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanggalYActionPerformed(evt);
            }
        });

        jLabel31.setText("Perlengkapan");

        bodyCapCB.setText("Body Cap");
        bodyCapCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bodyCapCBActionPerformed(evt);
            }
        });

        hotShoeCB.setText("Hot Shoe");
        hotShoeCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotShoeCBActionPerformed(evt);
            }
        });

        rearCapCB.setText("Rear Cap");
        rearCapCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rearCapCBActionPerformed(evt);
            }
        });

        taliCB.setText("Tali");
        taliCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taliCBActionPerformed(evt);
            }
        });

        lensCapCB.setText("Lens Cap");
        lensCapCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lensCapCBActionPerformed(evt);
            }
        });

        filterUVCB.setText("UV Filter Lens");
        filterUVCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterUVCBActionPerformed(evt);
            }
        });

        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        statusPengambilan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selesai", "Batal" }));

        jLabel1.setText("+62");

        ketPeng.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pembersihan", "Ganti Lampu Flash", "Reset Sistem", "Ganti Lensa", "Kamera Diambil" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel24))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                                .addComponent(namaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel19))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(KodeUnit, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                                    .addComponent(noNotaTxt))))
                        .addGap(211, 211, 211))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29)
                            .addComponent(jLabel27)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel30)
                            .addComponent(jLabel31)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addGap(109, 109, 109)
                                .addComponent(ketPeng, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(statusPengambilan, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel25)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel26)
                                        .addGap(105, 105, 105)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(noHP, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(232, 232, 232)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(keluhan, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(merek, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(tanggalD, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tanggalM, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tanggalY, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(alamatToko, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(KsiUnit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(bodyCapCB, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(bodyCapSpnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(hotShoeCB, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(hotShoeSpnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lensCapSpnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lensCapCB, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rearCapCB, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(rearCapSpnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(taliCB, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(taliSpnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(filterUVSpnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(filterUVCB))))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelBtn)
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(noNotaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(KodeUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(namaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(statusPengambilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(noHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(keluhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(ketPeng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(merek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(tanggalD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tanggalM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tanggalY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(KsiUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(alamatToko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel31)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bodyCapCB)
                        .addComponent(hotShoeCB)
                        .addComponent(lensCapCB)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bodyCapSpnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hotShoeSpnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lensCapSpnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rearCapCB)
                    .addComponent(taliCB)
                    .addComponent(filterUVCB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filterUVSpnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rearCapSpnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taliSpnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn)
                    .addComponent(cancelBtn))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void noNotaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noNotaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noNotaTxtActionPerformed

    private void KodeUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KodeUnitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KodeUnitActionPerformed

    private void KsiUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KsiUnitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KsiUnitActionPerformed

    private void alamatTokoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamatTokoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamatTokoActionPerformed

    private void namaPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaPelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaPelangganActionPerformed

    private void noHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noHPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noHPActionPerformed

    private void alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamatActionPerformed

    private void keluhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluhanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keluhanActionPerformed

    private void tanggalDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanggalDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggalDActionPerformed

    private void merekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_merekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_merekActionPerformed

    private void tanggalMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanggalMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggalMActionPerformed

    private void tanggalYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanggalYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggalYActionPerformed

    private void bodyCapCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bodyCapCBActionPerformed
        if(bodyCapCB.isSelected()){
            bodyCapSpnr.setEnabled(true);
        } else{
            bodyCapSpnr.setEnabled(false);
        }
    }//GEN-LAST:event_bodyCapCBActionPerformed

    private void hotShoeCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotShoeCBActionPerformed
        if(hotShoeCB.isSelected()){
            hotShoeSpnr.setEnabled(true);
        } else{
            hotShoeSpnr.setEnabled(false);
        }
    }//GEN-LAST:event_hotShoeCBActionPerformed

    private void lensCapCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lensCapCBActionPerformed
        if(lensCapCB.isSelected()){
            lensCapSpnr.setEnabled(true);
        } else{
            lensCapSpnr.setEnabled(false);
        }
    }//GEN-LAST:event_lensCapCBActionPerformed

    private void rearCapCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rearCapCBActionPerformed
        if(rearCapCB.isSelected()){
            rearCapSpnr.setEnabled(true);
        } else{
            rearCapSpnr.setEnabled(false);
        }
    }//GEN-LAST:event_rearCapCBActionPerformed

    private void taliCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taliCBActionPerformed
        if(taliCB.isSelected()){
            taliSpnr.setEnabled(true);
        } else{
            taliSpnr.setEnabled(false);
        }
    }//GEN-LAST:event_taliCBActionPerformed

    private void filterUVCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterUVCBActionPerformed
        if(filterUVCB.isSelected()){
            filterUVSpnr.setEnabled(true);
        } else{
            filterUVSpnr.setEnabled(false);
        }
    }//GEN-LAST:event_filterUVCBActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        int opm = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin untuk menambahkan data?", "Perhatian!" ,JOptionPane.OK_CANCEL_OPTION);
        if(opm==JOptionPane.OK_OPTION){
            String noNota = noNotaTxt.getText();
            String kodeUnit = KodeUnit.getText();
            String namaP = namaPelanggan.getText();
            String status = statusPengambilan.getModel().getSelectedItem().toString();
            String noHPP = noHP.getText();
            String alamatP = alamat.getText();
            String kel = keluhan.getText();
            String ket = ketPeng.getModel().getSelectedItem().toString();
            String model = merek.getText();
            String hari = tanggalD.getText();
            String bulan = tanggalM.getText();
            String tahun = tanggalY.getText();
            String ksi = KsiUnit.getModel().getSelectedItem().toString();
            String alamatT = alamatToko.getModel().getSelectedItem().toString();
            int bd=0;
            int hs=0;
            int lc=0;
            int rc=0;
            int uv=0;
            int tali=0;

            //FD 5
            ResultSet resultSet = null;
                String selectSql = String.format("INSERT INTO FD_5(Nama_Pelanggan,Alamat_Pelanggan,WA_Pelanggan)"
                        + " VALUES ('%s','%s','%s')", 
                        namaP, alamatP,noHPP);
                try (Connection connection = DriverManager.getConnection(connectionUr1);) {
                    Statement statement = connection.createStatement();
                    resultSet = statement.executeQuery(selectSql);
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            //FD 3
            resultSet = null;
                selectSql = String.format("INSERT INTO FD_3(No_Nota, Alamat_Toko, Nama_Toko, Nama_Pelanggan, Tanggal, Status_Pengambilan)"
                        + " VALUES ('%s','%s','MDS', '%s', '%s/%s/%s', '%s')", 
                        noNota,alamatT,namaP, hari, bulan,tahun, status);
                try (Connection connection = DriverManager.getConnection(connectionUr1);) {
                    Statement statement = connection.createStatement();
                    resultSet = statement.executeQuery(selectSql);
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            //FD 8
            resultSet = null;
                selectSql = String.format("INSERT INTO FD_8(Kode_Unit, Model_Barang)"
                        + " VALUES ('%s','%s')", 
                        kodeUnit,model);
                try (Connection connection = DriverManager.getConnection(connectionUr1);) {
                    Statement statement = connection.createStatement();
                    resultSet = statement.executeQuery(selectSql);
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            //FD 1
            resultSet = null;
                selectSql = String.format("INSERT INTO FD_1(No_Nota,Kode_Unit,Kondisi_Unit)"
                        + " VALUES ('%s','%s','%s')", 
                        noNota, kodeUnit,ksi);
                try (Connection connection = DriverManager.getConnection(connectionUr1);) {
                    Statement statement = connection.createStatement();
                    resultSet = statement.executeQuery(selectSql);
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            //FD 2
            resultSet = null;
                selectSql = String.format("INSERT INTO FD_2(Keluhan,Kode_Unit,Ket_Pengerjaan)"
                        + " VALUES ('%s','%s','%s')", 
                        kel, kodeUnit,ket);
                try (Connection connection = DriverManager.getConnection(connectionUr1);) {
                    Statement statement = connection.createStatement();
                    resultSet = statement.executeQuery(selectSql);
                } catch (SQLException e) {
                    e.printStackTrace();
                }

            //FD 7
            if(bodyCapCB.isSelected()){
                bd = Integer.parseInt(bodyCapSpnr.getModel().getValue().toString());
                resultSet = null;
                selectSql = String.format("INSERT INTO FD_7(Kode_Unit, Perlengkapan, Jumlah_Barang) VALUES ('%s','Body Cap','%d')",
                                            kodeUnit,bd);
                try (Connection connection = DriverManager.getConnection(connectionUr1);) {
                    Statement statement = connection.createStatement();
                    resultSet = statement.executeQuery(selectSql);
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
            if(hotShoeCB.isSelected()){
                hs = Integer.parseInt(hotShoeSpnr.getModel().getValue().toString());
                resultSet = null;
                selectSql = String.format("INSERT INTO FD_7(Kode_Unit, Perlengkapan, Jumlah_Barang) VALUES ('%s','Hot Shoe','%d')",
                                            kodeUnit,hs);
                try (Connection connection = DriverManager.getConnection(connectionUr1);) {
                    Statement statement = connection.createStatement();
                    resultSet = statement.executeQuery(selectSql);
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
            if(lensCapCB.isSelected()){
                lc = Integer.parseInt(lensCapSpnr.getModel().getValue().toString());
                resultSet = null;
                selectSql = String.format("INSERT INTO FD_7(Kode_Unit, Perlengkapan, Jumlah_Barang) VALUES ('%s','Lens Cap','%d')",
                                            kodeUnit,lc);
                try (Connection connection = DriverManager.getConnection(connectionUr1);) {
                    Statement statement = connection.createStatement();
                    resultSet = statement.executeQuery(selectSql);
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
            if(rearCapCB.isSelected()){
                rc = Integer.parseInt(rearCapSpnr.getModel().getValue().toString());
                resultSet = null;
                selectSql = String.format("INSERT INTO FD_7(Kode_Unit, Perlengkapan, Jumlah_Barang) VALUES ('%s','Rear Cap','%d')",
                                        kodeUnit,rc);
                try (Connection connection = DriverManager.getConnection(connectionUr1);) {
                    Statement statement = connection.createStatement();
                    resultSet = statement.executeQuery(selectSql);
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
            if(filterUVCB.isSelected()){
                uv = Integer.parseInt(filterUVSpnr.getModel().getValue().toString());
                resultSet = null;
                selectSql = String.format("INSERT INTO FD_7(Kode_Unit, Perlengkapan, Jumlah_Barang) VALUES ('%s','UV filter','%d')",
                                        kodeUnit,uv);
                try (Connection connection = DriverManager.getConnection(connectionUr1);) {
                    Statement statement = connection.createStatement();
                    resultSet = statement.executeQuery(selectSql);
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
            if(taliCB.isSelected()){
                tali = Integer.parseInt(taliSpnr.getModel().getValue().toString());
                resultSet = null;
                selectSql = String.format("INSERT INTO FD_7(Kode_Unit, Perlengkapan, Jumlah_Barang) VALUES ('%s','tali','%d')",
                                        kodeUnit,tali);
                try (Connection connection = DriverManager.getConnection(connectionUr1);) {
                    Statement statement = connection.createStatement();
                    resultSet = statement.executeQuery(selectSql);
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
            Form_Basdat formbd = new Form_Basdat();
            formbd.setVisible(true);
            this.setVisible(false);
        }
        
        
    }//GEN-LAST:event_addBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        int opm = JOptionPane.showConfirmDialog(null, "Apakah Anda tidak jadi menambahkan data?", "Perhatian!" ,JOptionPane.OK_CANCEL_OPTION);
        Form_Basdat formbd = new Form_Basdat();
        if(opm==JOptionPane.OK_OPTION){
            formbd.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_cancelBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField KodeUnit;
    private javax.swing.JComboBox<String> KsiUnit;
    private javax.swing.JButton addBtn;
    private javax.swing.JTextField alamat;
    private javax.swing.JComboBox<String> alamatToko;
    private javax.swing.JCheckBox bodyCapCB;
    private javax.swing.JSpinner bodyCapSpnr;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JCheckBox filterUVCB;
    private javax.swing.JSpinner filterUVSpnr;
    private javax.swing.JCheckBox hotShoeCB;
    private javax.swing.JSpinner hotShoeSpnr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField keluhan;
    private javax.swing.JComboBox<String> ketPeng;
    private javax.swing.JCheckBox lensCapCB;
    private javax.swing.JSpinner lensCapSpnr;
    private javax.swing.JTextField merek;
    private javax.swing.JTextField namaPelanggan;
    private javax.swing.JTextField noHP;
    private javax.swing.JTextField noNotaTxt;
    private javax.swing.JCheckBox rearCapCB;
    private javax.swing.JSpinner rearCapSpnr;
    private javax.swing.JComboBox<String> statusPengambilan;
    private javax.swing.JCheckBox taliCB;
    private javax.swing.JSpinner taliSpnr;
    private javax.swing.JTextField tanggalD;
    private javax.swing.JTextField tanggalM;
    private javax.swing.JTextField tanggalY;
    // End of variables declaration//GEN-END:variables
}
